server:
  port: 8004
spring:
  application:
    name: AUTH-SERVICE
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/D14-AI
    password: Ga.4567.
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/